<?php

namespace App\Controller;

use App\Form\GestionProfilType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class ParticipantController extends AbstractController
{
    /**
     * @Route("/", name="connexion")
     * @param AuthenticationUtils $authenticationUtils
     * @return Response
     */
    public function connexion(AuthenticationUtils $authenticationUtils): Response
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render("security/connexion.html.twig", ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/logout", name="logout")
     */
    public function logout(): Response
    {}

    /**
     * @Route("/profil/{id}", name= "gestion_profil"),
     * method={"GET"})
     * @param Request $request
     * @param EntityManagerInterface $em
     * @return Response
     */
    public function mettreAJourProfil (Request $request, EntityManagerInterface $em): Response
    {
        $user = $this->getUser();
        //création du formulaire
        $formulaireGestionProfil = $this->createForm(GestionProfilType::class, $user);

        //récupération de la saisie utilisateur
        $formulaireGestionProfil->handleRequest($request);

        //si le formulaire est soumis
        if ($formulaireGestionProfil->isSubmitted() && $formulaireGestionProfil->isValid()) {

            $fichierPhoto = $formulaireGestionProfil->get('photo')->getData();

            $NomFichierPhoto = $this->generateUniqueFileName().'.'.$fichierPhoto->guessExtension();

            try {
                $fichierPhoto->move(
                    $this->getParameter('photo_profil_directory'),
                    $NomFichierPhoto
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }

            // updates the 'brochure' property to store the PDF file name
            // instead of its contents
            $user->setPhoto($NomFichierPhoto);

            $em->flush();

            $this->addFlash('success','Profil modifié avec succès !');


            // return $this->redirectToRoute ('gestion_profil');

        }

        return $this->render("participant/monProfil.html.twig", ['user' => $user,
            "formulaireGestionProfil" => $formulaireGestionProfil->createView()
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


}
